# 02-使用numpy计算矩阵


常用NumPy数组属性：
`ndarray.shape`:
- 含义：每个维度的大小
- 返回：tuple
- 用途：判断矩阵是(m,n)还是(batch,seq,dim)

`ndarray.ndim`
- 含义：维度数(轴数)
- 用途：判断是一维/二维/三维

`ndarray.size`
- 含义：元素总数 
- 等价于shape各维度乘积

`ndarray.dtype`
- 含义：元素类型(int32/float64)
- 用途：数值计算/内存分析

In [ ]:
import numpy as np

a = np.arange(24)
print(a.ndim)# a现在只有一个维度

b = a.reshape(2,4,3)

print(b.ndim) #b现在有三个维度

1
3


In [ ]:
import numpy as np

a = np.array([[1,2,3],[4,5,6]])
print(a.shape)# a现在的shape是(2,3)二行三列
a.shape = (3,2)#原地调整a的shape为三行二列(不推荐)
b = np.reshape(a,(3,2))#更加函数式

print(a)
print(b)

(2, 3)
[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]


/var/folders/fx/djkfqjhj39n4_54qr4pljs3r0000gn/T/ipykernel_19051/227651406.py:5: DeprecationWarning: Setting the shape on a NumPy array has been deprecated in NumPy 2.5.
As an alternative, you can create a new view using np.reshape (with copy=False if needed).
  a.shape = (3,2)#原地调整a的shape为三行二列


### 为什么NumPy更偏好reshape？
shape：
| 问题            | 说明             |
| ------------- | -------------- |
| 不表达 copy/view | 你不知道是否共享内存     |
| 不表达失败条件       | shape 不兼容会直接报错 |
| 不适合函数式链       | 不可嵌入 pipeline  |

reshape的优势
- 可组合(composable)
- 可控(control over memory)


In [19]:
#创建空数组

import numpy as np

x = np.empty([3,2],dtype = int)
print(x)

[[1 2]
 [3 4]
 [5 6]]


#### numpy.zeros
创建指定大小的数组，数组元素以0来填充

`numpy.zeros(shape,dtype = float,order = 'C')`


| 参数|	描述    |
|---------|-----------|
| shape|	数组形状 |
| dtype|	数据类型，可选 |
| order|	'C' 用于 C 的行数组，或者 'F' 用于 FORTRAN 的列数组 |



In [23]:
import numpy as np

x = np.zeros((2,2),float)
print(x)

[[0. 0.]
 [0. 0.]]


### NumPy从已有的数组创建数组

**numpy.asarray**
numpy.asarray类似于numpy.array，但是numpy.asarray的参数只有三个，比numpy.array少两个
`numpy.asarray(a,dtype = None,order = None)`


In [ ]:
#example list->ndarray
import numpy as np

x= [1,2,3]
a = np.asarray(x)
print(a)

#example tuple->ndarray

y = (1,2,3)
b = np.asarray(y)
print(b)

x =  [(1,2,3),(4,5)] 
# a = np.asarray(x)  新版本中严格禁止ragged ndarray
a = np.asarray(x,dtype = object)#允许不规则，变成python对象数组
print (a)
print(a.shape)#列数不是规则的，无法列出来

[1 2 3]
[1 2 3]
[(1, 2, 3) (4, 5)]
(2,)
